#!/bin/bash

if [[ -z "$1" ]]; then
    echo
    read -p "Which function do you want to call ? : " FUNC
else 
    FUNC=$1 
fi

case $FUNC in
    -upt) FUNC="Update" ;;
    -trf) FUNC="Transfert" ;;
    -trfVM) FUNC="TransfertFromDebianVM" ;;
    -add) FUNC="AddRepository" ;;
    -rm) FUNC="RemoveRepository" ;;
    -open) FUNC="OpenFiles" ;;
    -help) 
        echo -e "\nChoose a parameter between :\n\n-upt    ->  update repositories\n-trf    ->  transfert from a VM to your current device\n-trfVM  ->  transfert from Lapfips' VM to your current device\n-add    ->  add a new repository to update\n-rm     ->  remove a repository from update\n-open   ->  open every file in the current folder"
        exit 0
        ;;
    *) 
        echo -e "\nInvalid parameter. Try again"
        exit 1
        ;;
esac

function_path="$USERPROFILE/.progFunctions/.$FUNC"

if [[ -f "$function_path" ]]; then
    bash "$function_path" $2 $3 $4 $5 $6 $7 $8 $9
else
    echo -e "\nFunction script $function_path not found."
    exit 1
fi
